baseURL = "https://hsantanna.org/"
title = "Hugo Sant'Anna"
languageCode = "en-us"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true
buildDrafts = false
buildFuture = false
summaryLength = 30
timeZone = "America/New_York"

[pagination]
  pagerSize = 100

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[frontmatter]
  date = ["date", "publishDate", "lastmod"]

[services.rss]
  limit = 20
