description = "Hugo Sant'Anna is an Assistant Professor of Economics at the University of Alabama at Birmingham, working on labor economics, immigration, and difference-in-differences methods."
mainSections = ["posts"]
dateFormat = "January 2, 2006"
socialImage = "img/social.jpg"

[author]
  name = "Hugo Sant'Anna"
  title = "Assistant Professor of Economics"
  department = "Collat School of Business"
  institution = "University of Alabama at Birmingham"
  institutionURL = "https://www.uab.edu/business/home/"
  email = "hsantanna@uab.edu"
  photo = "img/profile.jpg"
  cv = "/files/hsantannaCV.pdf"
  scholar = "https://scholar.google.com/citations?&user=4NIRsiYAAAAJ"
  github = "https://github.com/hugosantanna"
  twitter = "https://twitter.com/hsantanna"
  readingGroup = "https://uga-metrics.github.io/"
